FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y byobu curl git htop man unzip wget nodejs npm netstat
RUN netstat -lt
RUN cd ~
COPY . deltachat-desktop/
WORKDIR deltachat-desktop
CMD [ls -l]
